import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {  Heading, Text }  from '@sonicaweb3/react'

export default function Cancel() {
  return (
    <>
      <Head>
        <title>Success - Subscriptions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Heading variant='big-title' color='primaryColor600'>Success! Subscription as payed.</Heading>
        <Text variant='body' color='neutralColor400'>Now, you can deploy contract in mainnet!</Text>
      </main>
    </>
  )
}
