import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { stripe } from '@/lib/stripe'
import { GetServerSideProps, GetStaticProps } from 'next'
import Stripe from 'stripe'
import { Box, Heading, Text }  from '@sonicaweb3/react'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

interface HomeProps {
  products: {
    id: string;
    name: string;
    price: number;
    description: string;
    image: string;    
  }[]
}

export default function Home({ products }:HomeProps) {
  return (
    <>
      <Head>
        <title>Sonica - Subscriptions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        
        

      </main>
    </>
  )
}



export const getServerSideProps: GetServerSideProps<any, {id: string}> = async ({ params }) => {
    const planId = params?.id;
  const planData = await stripe.products.retrieve(planId!,{
    expand: ['data.default_price'],
  });

  
    const price = planData.default_price as Stripe.Price;

    const priceFormatted = new Intl.NumberFormat('en-US', {'currency': 'USD', 'style': 'currency'})
                                .format(price.unit_amount! / 100);

    const plan = {
        id: planData.id,
        name: planData.name,
        price: priceFormatted,
        description: planData.description,
        image: planData.images[0] ?? '',
    }


    return {
    props: {
        products: plan,
    },
    // revalidate: 60 * 60 * 2, // 2 hours
    }
}
